import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useContext } from "react";
import Layout from "@/components/Layout/Main";
import Sidebar from "@/components/Sidebar";
import MovieContext from "@/store/Movie-contest";
import Movietitle from "@/components/MovieDetail/MovieTitle";
import Herosection from "@/components/MovieDetail/HeroSection";
import MovieAbout from "@/components/MovieDetail/MovieAbout";
import MovieStills from "@/components/MovieDetail/MovieStills";

export default function Home() {
  const movieCtx = useContext(MovieContext);
  return (
    <div>
      <Head>
        <title>Movie Detail Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </Head>

      <div className="flex">
        <Sidebar />
        <div className="w-full xl:11/12">
          <Layout>
            <div className="w-full xl:w-full">
              <div
                className="w-full h-full p-[12px] xl:p-[35px] bg-no-repeat bg-right xl:bg-right-top"
                style={{
                  backgroundImage: `linear-gradient(to bottom,rgba(0,0,0,0),#101010),url(${movieCtx.movieDetail.movieBanner})`,
                }}
              >
                <div
                  className="w-full h-full"
                  style={{
                    background:
                      "linear-gradient(to bottom,rgba(0,0,0,0),#101010)",
                  }}
                >
                  <Movietitle />
                  <Herosection />
                  <MovieAbout />
                  <MovieStills />
                </div>
              </div>
            </div>
          </Layout>
        </div>
      </div>
    </div>
  );
}
