export const trendingMovies = [
  {
    backgroundImg: "/images/tr0.png",
    title: "Hridayam",
    year: "2022",
    genre: "Movies",
    views: "3 203 184",
  },
  {
    backgroundImg: "/images/tr2.png",
    title: "X",
    year: "2022",
    genre: "Movies",
    views: "167 405",
  },
  {
    backgroundImg: "/images/tr1.png",
    title: "Sandakozhi 2",
    year: "2018",
    genre: "Movies",
    views: "49 598",
  },
  {
    backgroundImg: "/images/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
  },
  {
    backgroundImg: "/images/tr3.png",
    title: "Bhajarangi 2",
    year: "2021",
    genre: "Movies",
    views: "212 976",
  },
  {
    backgroundImg: "/images/tr6.png",
    title: "Jatt Brothers",
    year: "2022",
    genre: "Movies",
    views: "91 742",
  },
  {
    backgroundImg: "/images/tr8.png",
    title: "Mufti",
    year: "2017",
    genre: "Movies",
    views: "16 500",
  },
  {
    backgroundImg: "/images/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
  },
];
export const popularMovies = [
  {
    backgroundImg: "/images/tr0.png",
    title: "Hridayam",
    year: "2022",
    genre: "Movies",
    views: "3 203 184",
    rating: "8.0",
  },
  {
    backgroundImg: "/images/tr2.png",
    title: "X",
    year: "2022",
    genre: "Movies",
    views: "167 405",
    rating: "8.5",
  },
  {
    backgroundImg: "/images/tr1.png",
    title: "Sandakozhi 2",
    year: "2018",
    genre: "Movies",
    views: "49 598",
    rating: "8.7",
  },
  {
    backgroundImg: "/images/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "9.3",
  },
  {
    backgroundImg: "/images/tr3.png",
    title: "Bhajarangi 2",
    year: "2021",
    genre: "Movies",
    views: "212 976",
    rating: "9.5",
  },
  {
    backgroundImg: "/images/tr6.png",
    title: "Jatt Brothers",
    year: "2022",
    genre: "Movies",
    views: "91 742",
    rating: "8.0",
  },
  {
    backgroundImg: "/images/tr8.png",
    title: "Mufti",
    year: "2017",
    genre: "Movies",
    views: "16 500",
    rating: "9.8",
  },
  {
    backgroundImg: "/images/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "7.5",
  },
];

export const moreMovies = [
  {
    backgroundImg: "/images/tr0.png",
    title: "Hridayam",
    year: "2022",
    genre: "Movies",
    views: "3 203 184",
    rating: "6.3",
  },
  {
    backgroundImg: "/images/tr2.png",
    title: "X",
    year: "2022",
    genre: "Movies",
    views: "167 405",
    rating: "7.3",
  },
  {
    backgroundImg: "/images/tr1.png",
    title: "Sandakozhi 2",
    year: "2018",
    genre: "Movies",
    views: "49 598",
    rating: "8.3",
  },
  {
    backgroundImg: "/images/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "9.0",
  },
  {
    backgroundImg: "/images/tr3.png",
    title: "Bhajarangi 2",
    year: "2021",
    genre: "Movies",
    views: "212 976",
    rating: "8.7",
  },
  {
    backgroundImg: "/images/tr6.png",
    title: "Jatt Brothers",
    year: "2022",
    genre: "Movies",
    views: "91 742",
    rating: "9.8",
  },
  {
    backgroundImg: "/images/tr8.png",
    title: "Mufti",
    year: "2017",
    genre: "Movies",
    views: "16 500",
    rating: "5.8",
  },
  {
    backgroundImg: "/images/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "8.2",
  },
];

export const series = [
  {
    backgroundImg: "/images/tr0.png",
    title: "Hridayam",
    year: "2022",
    genre: "Movies",
    views: "3 203 184",
    rating: "10",
  },
  {
    backgroundImg: "/images/tr2.png",
    title: "X",
    year: "2022",
    genre: "Movies",
    views: "167 405",
    rating: "4.5",
  },
  {
    backgroundImg: "/images/tr1.png",
    title: "Sandakozhi 2",
    year: "2018",
    genre: "Movies",
    views: "49 598",
    rating: "7.8",
  },
  {
    backgroundImg: "/images/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "9.8",
  },
  {
    backgroundImg: "/images/tr3.png",
    title: "Bhajarangi 2",
    year: "2021",
    genre: "Movies",
    views: "212 976",
    rating: "7.6",
  },
  {
    backgroundImg: "/images/tr6.png",
    title: "Jatt Brothers",
    year: "2022",
    genre: "Movies",
    views: "91 742",
    rating: "7.7",
  },
  {
    backgroundImg: "/images/tr8.png",
    title: "Mufti",
    year: "2017",
    genre: "Movies",
    views: "16 500",
    rating: "9.0",
  },
  {
    backgroundImg: "/images/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "8.7",
  },
];

export const cartoons = [
  {
    backgroundImg: "/images/tr0.png",
    title: "Hridayam",
    year: "2022",
    genre: "Movies",
    views: "3 203 184",
    rating: "5.5",
  },
  {
    backgroundImg: "/images/tr2.png",
    title: "X",
    year: "2022",
    genre: "Movies",
    views: "167 405",
    rating: "7.6",
  },
  {
    backgroundImg: "/images/tr1.png",
    title: "Sandakozhi 2",
    year: "2018",
    genre: "Movies",
    views: "49 598",
    rating: "8.7",
  },
  {
    backgroundImg: "/images/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "9.6",
  },
  {
    backgroundImg: "/images/tr3.png",
    title: "Bhajarangi 2",
    year: "2021",
    genre: "Movies",
    views: "212 976",
    rating: "4.5",
  },
  {
    backgroundImg: "/images/tr6.png",
    title: "Jatt Brothers",
    year: "2022",
    genre: "Movies",
    views: "91 742",
    rating: "6",
  },
  {
    backgroundImg: "/images/tr8.png",
    title: "Mufti",
    year: "2017",
    genre: "Movies",
    views: "16 500",
    rating: "8.7",
  },
  {
    backgroundImg: "/images/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "4.3",
  },
];

export const tv = [
  {
    backgroundImg: "/images/tr0.png",
    title: "Hridayam",
    year: "2022",
    genre: "Movies",
    views: "3 203 184",
    rating: "5",
  },
  {
    backgroundImg: "/images/tr2.png",
    title: "X",
    year: "2022",
    genre: "Movies",
    views: "167 405",
    rating: "6.7",
  },
  {
    backgroundImg: "/images/tr1.png",
    title: "Sandakozhi 2",
    year: "2018",
    genre: "Movies",
    views: "49 598",
    rating: "8.5",
  },
  {
    backgroundImg: "/images/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "3.4",
  },
  {
    backgroundImg: "/images/tr3.png",
    title: "Bhajarangi 2",
    year: "2021",
    genre: "Movies",
    views: "212 976",
    rating: "10",
  },
  {
    backgroundImg: "/images/tr6.png",
    title: "Jatt Brothers",
    year: "2022",
    genre: "Movies",
    views: "91 742",
    rating: "8.6",
  },
  {
    backgroundImg: "/images/tr8.png",
    title: "Mufti",
    year: "2017",
    genre: "Movies",
    views: "16 500",
    rating: "6.7",
  },
  {
    backgroundImg: "/images/tr4.png",
    title: "Njan Prakasan",
    year: "2018",
    genre: "Movies",
    views: "27 757",
    rating: "6.8",
  },
];

export const movieDetail = {
  movieTitle: "You are Not My Mother (2021)",
  movieBanner: "images/bgg.png",
  description:
    "In a North Dublin housing estate Char's mother goes missing. When she returns Char is determined to uncover the truth of her disappearance and unearth the dark secrets of her family.",
  cardBanner: "images/md1.jpg",
  videoUrl: "https://www.w3schools.com/tags/movie.mp4",
  imdbRating: "5.8",
  metaScoreRating: "74",
  saiScoreRating: "9",
  stills: [
    "https://saicord.com/uploads/posts/2022-07/1656670492_6.jpg",
    "https://saicord.com/uploads/posts/2022-07/1656670496_1.jpg",
    "https://saicord.com/uploads/posts/2022-07/1656670501_2.jpg",
    "https://saicord.com/uploads/posts/2022-07/1656670508_3.jpg",
    "https://saicord.com/uploads/posts/2022-07/1656670512_4.jpg",
    "https://saicord.com/uploads/posts/2022-07/1656670516_5.jpg",
  ],
  movieDirector: "Kate Dolan",
  Stars: "Hazel Doupe,Carolyn Bracken,Paul Reid",
  Genres: "Drama,Horror",
  Language: "English",
  Company: "Bankside Films,Fantastic Films,Screen Island",
  Writers: "Kate Dolan",
  Tagline: "<<Every Family Has Their Secrets.>>",
  Country: "Ireland",
  Year: "2021",
  Runtime: "93 min",
};

export const slideshowMovies = [
  {
    title: "You are not my mother",
    description:
      "In a North Dublin estate Char's mother goes missing. When she return Char is determined to uncover the truth of her disapperance and unearth the dark secrets of her family...",
    year: "2021",
    genre: "Horror",
    rating: "9",
    backgroundImg: "/images/sg1.png",
    img: "/images/bgg.png",
  },
  {
    title: "Attack on Finland",
    description:
      "Finland's Independence Day celebration on December 6 is crudely interrupted by an attack on the Presidential Palace. A set of distinguished guests are taken as hostages. Security service officer Max...",
    year: "2021",
    genre: "Action",
    rating: "8",
    backgroundImg: "/images/sg2.png",
    img: "/images/bgg2.jpg",
  },
  {
    title: "Chicken Hair and Tail",
    description:
      "Follows a young hero born half chicken and half hare. Eager to fit in and feel loved in spite of his differences, he is obsessed by adventuring in spite of his clumsiness....",
    year: "2022",
    genre: "cartoon",
    rating: "10",
    backgroundImg: "/images/sg3.png",
    img: "/images/bgg3.jpg",
  },
];
