import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useContext } from "react";
import Layout from "@/components/Layout/Main";
import Sidebar from "@/components/Sidebar";
import Contactus from "@/components/Common/Contactus";
import Slideshow from "@/components/Home/Slideshow";
import Trending from "@/components/Home/Trending";
import Commonslider from "@/components/Home/CommonSlider";
import MovieContext from "@/store/Movie-contest";
import Recommended from "@/components/Home/Recommended";
const Home = () => {
  const ctx = useContext(MovieContext);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </Head>

      <div className="flex">
        <Sidebar />
        <div className="w-11/12 xl:11/12">
          <Layout>
            <Contactus />
            <Slideshow />
            <Trending />
            <div id="popularMovies">
              <Commonslider type={"Popular"} movies={ctx.popularMovies} />
            </div>
            <div id="movies">
              <Commonslider type={"Movies"} movies={ctx.moreMovies} />
            </div>
            <div id="series">
              <Commonslider type={"Series"} movies={ctx.series} />
            </div>
            <div id="cartoons">
              <Commonslider type={"Cartoons"} movies={ctx.cartoons} />
            </div>
            <div id="tv">
              <Commonslider type={"Tv+"} movies={ctx.tv} />
            </div>
            <div id="recommended">
              <Recommended />
            </div>
          </Layout>
        </div>
      </div>
    </div>
  );
};
export default Home;
